name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Rush CI
          email: rush-ci@example.com
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Update
        run: node common/scripts/install-run-rush.js update
      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose
